DROP TABLE  IF EXISTS [TABLE_NAME];

/**********************************/
/* Table Name: [Description] */
/**********************************/
CREATE TABLE [TABLE_NAME](
[DDL_COLUMN]
	ISDEL	 	VARCHAR(1)	DEFAULT	'Y'		NOT NULL	COMMENT '사용여부',
	CREATED	 	DATETIME	DEFAULT	NOW()				COMMENT '등록일시',
	CREATED_ID	VARCHAR(20)								COMMENT '등록자ID',
	MODIFIED	DATETIME	DEFAULT	NOW()				COMMENT '수정일시',
	MODIFIED_ID	VARCHAR(20)								COMMENT '수정자ID'
) COMMENT='[Description]';
ALTER TABLE [TABLE_NAME] ADD CONSTRAINT IDX_[TABLE_NAME]_PK PRIMARY KEY ([FirstColumn]);

-- DELETE FROM JNITSEQ WHERE TABLE_NAME = '[IDGEN_TABLE_NAME]';
INSERT INTO JNITSEQ(TABLE_NAME, NEXT_ID) VALUES ('[IDGEN_TABLE_NAME]', '1');