DROP TABLE [TABLE_NAME] CASCADE CONSTRAINTS;

/**********************************/
/* Table Name: [Description] */
/**********************************/
CREATE TABLE [TABLE_NAME](
[DDL_COLUMN]
	REG_DT		DATE			DEFAULT	SYSDATE 	NOT NULL,
	RGTR_ID		VARCHAR2(20)             			NOT NULL,
	MDFCN_DT	DATE			DEFAULT	SYSDATE  	NOT NULL,
	MDFR_ID		VARCHAR2(20)						NOT NULL,
	DEL_YN	 	CHAR(1)			DEFAULT	'N'			NOT NULL
);
ALTER TABLE [TABLE_NAME] ADD CONSTRAINT IDX_[TABLE_NAME]_PK PRIMARY KEY ([FirstColumn]);

COMMENT ON TABLE [TABLE_NAME] is '[Description] 테이블';
[DDL_COMMENT]
COMMENT ON COLUMN [TABLE_NAME].REG_DT IS '등록일시';
COMMENT ON COLUMN [TABLE_NAME].RGTR_ID IS '등록자아이디';
COMMENT ON COLUMN [TABLE_NAME].MDFCN_DT IS '수정일시';
COMMENT ON COLUMN [TABLE_NAME].MDFR_ID IS '수정자아이디';
COMMENT ON COLUMN [TABLE_NAME].DEL_YN IS '삭제여부';


-- ID GENERATE TYPE
-- DELETE FROM JNITSEQ WHERE TABLE_NAME = '[IDGEN_TABLE_NAME]';
-- INSERT INTO JNITSEQ(TABLE_NAME, NEXT_ID) VALUES ('[IDGEN_TABLE_NAME]', '1');

-- SEQUENCE TYPE
-- DROP SEQUENCE SEQ_[TABLE_NAME];
CREATE SEQUENCE SEQ_[TABLE_NAME] START WITH 1 INCREMENT BY 1;
-- GRANT SELECT ON SEQ_[TABLE_NAME] TO [권한을 부여할 계정];
-- DROP PUBLIC SYNONYM SEQ_[TABLE_NAME];
-- CREATE PUBLIC SYNONYM SEQ_[TABLE_NAME] FOR SEQ_[TABLE_NAME];
