/* 공통그룹코드 */
DROP TABLE TB_CMMN_GROUP_CD;
CREATE TABLE TB_CMMN_GROUP_CD
(
	GROUP_CD             VARCHAR(6) NOT NULL ,
	UP_GROUP_CD          VARCHAR(6) NOT NULL ,
	GROUP_CD_NM          VARCHAR(100) NOT NULL ,
	GROUP_CD_LVL_VL      INTEGER(15) NULL ,
	GROUP_CD_SORT_SN     INTEGER(5) NULL ,
	GROUP_CD_CHG_YN      CHAR(1) DEFAULT  'N'  NOT NULL ,
	GROUP_CD_EXPLN       CLOB NULL ,
	REG_DT               DATETIME DEFAULT  SYSDATETIME  NOT NULL ,
	RGTR_ID              VARCHAR(20) NOT NULL ,
	MDFCN_DT             DATETIME DEFAULT  SYSDATETIME  NOT NULL ,
	MDFR_ID              VARCHAR(20) NOT NULL ,
	DEL_YN               CHAR(1) DEFAULT  'N'  NOT NULL 
);
ALTER TABLE TB_CMMN_GROUP_CD ADD CONSTRAINT PK1_TB_CMMN_GROUP_CD PRIMARY KEY (GROUP_CD);


/* 공통개별코드 */
DROP TABLE TB_CMMN_INDIV_CD;
CREATE TABLE TB_CMMN_INDIV_CD
(
	INDIV_CD             VARCHAR(6) NOT NULL ,
	GROUP_CD             VARCHAR(6) NOT NULL ,
	UP_INDIV_CD          VARCHAR(6) NOT NULL ,
	INDIV_CD_NM          VARCHAR(100) NOT NULL ,
	INDIV_CD_SORT_SN     INTEGER(5) NOT NULL ,
	INDIV_CD_CHG_YN      CHAR(1) DEFAULT  'N'  NOT NULL ,
	INDIV_CD_VL_FRST     VARCHAR(100) NULL ,
	INDIV_CD_VL_SCNDRY   VARCHAR(100) NULL ,
	INDIV_CD_VL_THIRD    VARCHAR(100) NULL ,
	INDIV_CD_EXPLN       VARCHAR(1000) NULL ,
	REG_DT               DATETIME DEFAULT  SYSDATETIME  NOT NULL ,
	RGTR_ID              VARCHAR(20) NOT NULL ,
	MDFCN_DT             DATETIME DEFAULT  SYSDATETIME  NOT NULL ,
	MDFR_ID              VARCHAR(20) NOT NULL ,
	DEL_YN               CHAR(1) DEFAULT  'N'  NOT NULL 
);
ALTER TABLE TB_CMMN_INDIV_CD ADD CONSTRAINT PK1_TB_CMMN_INDIV_CD PRIMARY KEY (INDIV_CD);
ALTER TABLE TB_CMMN_INDIV_CD ADD CONSTRAINT FK1_TB_CMMN_INDIV_CD FOREIGN KEY (GROUP_CD) REFERENCES TB_CMMN_GROUP_CD (GROUP_CD);


/* 권한그룹기본 */
DROP SERIAL SEQ_TB_AUTH_GRP_M;
CREATE SERIAL SEQ_TB_AUTH_GRP_M START WITH 1 INCREMENT BY 1;

DROP TABLE TB_AUTH_GRP_M;
CREATE TABLE TB_AUTH_GRP_M (
	AUTH_GRP_ID VARCHAR(20) NOT NULL,
	GRP_NM VARCHAR(50) NOT NULL,
	GRP_EXPLNT VARCHAR(500),
	REG_DT		DATETIME			DEFAULT	SYSDATETIME 	NOT NULL,
	RGTR_ID		VARCHAR(20)             			NOT NULL,
	MDFCN_DT	DATETIME			DEFAULT	SYSDATETIME  	NOT NULL,
	MDFR_ID		VARCHAR(20)						NOT NULL,
	DEL_YN	 	CHAR(1)			DEFAULT	'N'			NOT NULL
);
ALTER TABLE TB_AUTH_GRP_M ADD CONSTRAINT PK_TB_AUTH_GRP_M PRIMARY KEY (AUTH_GRP_ID);



/* 그룹메뉴권한관계 */
DROP SEQUENCE SEQ_TB_GRP_MENU_AUTH_R;
CREATE SERIAL SEQ_TB_GRP_MENU_AUTH_R START WITH 1 INCREMENT BY 1;
DROP table TB_GRP_MENU_AUTH_R;
CREATE TABLE TB_GRP_MENU_AUTH_R (
	AUTH_GRP_ID VARCHAR(20) NOT NULL,
	MENU_SN INTEGER(10) NOT NULL,
	STRE_AUTH_YN VARCHAR(1),
	REDNG_AUTH_YN VARCHAR(1),
	DEL_AUTH_YN VARCHAR(1),
	PRNTG_AUTH_YN VARCHAR(1),
	REG_DT DATETIME DEFAULT SYSDATETIME,
	RGTR_ID VARCHAR(20) DEFAULT 'SYSTEM'
);
ALTER TABLE TB_GRP_MENU_AUTH_R ADD CONSTRAINT PK_TB_GRP_MENU_AUTH_R PRIMARY KEY (AUTH_GRP_ID,MENU_SN);


/* 그룹메뉴권한변경이력 */
DROP SEQUENCE SEQ_TB_GRP_MENU_AUTH_CHNG_H;
CREATE SERIAL SEQ_TB_GRP_MENU_AUTH_CHNG_H START WITH 1 INCREMENT BY 1;
DROP TABLE TB_GRP_MENU_AUTH_CHNG_H;
CREATE TABLE TB_GRP_MENU_AUTH_CHNG_H (
	AUTH_GRP_ID VARCHAR(20) NOT NULL,
	MENU_SN INTEGER(10) NOT NULL,
	CHNG_HIST_SN INTEGER(10) NOT NULL,
	STRE_AUTH_YN VARCHAR(1),
	REDNG_AUTH_YN VARCHAR(1),
	DEL_AUTH_YN VARCHAR(1),
	PRNTG_AUTH_YN VARCHAR(1),
	REG_DT DATETIME DEFAULT SYSDATETIME,
	RGTR_ID VARCHAR(20) DEFAULT 'SYSTEM'
);
ALTER TABLE TB_GRP_MENU_AUTH_CHNG_H ADD CONSTRAINT PK_TB_GRP_MENU_AUTH_CHNG_H PRIMARY KEY (AUTH_GRP_ID,MENU_SN,CHNG_HIST_SN);


/* 개별메뉴권한관계 */
DROP SEQUENCE SEQ_TB_INDVLZ_MENU_AUTH_R;
CREATE SERIAL SEQ_TB_INDVLZ_MENU_AUTH_R START WITH 1 INCREMENT BY 1;
DROP TABLE TB_INDVLZ_MENU_AUTH_R;
CREATE TABLE TB_INDVLZ_MENU_AUTH_R (
	MBR_ID VARCHAR(20) NOT NULL,
	AUTH_GRP_ID VARCHAR(20) NOT NULL,
	MENU_SN INTEGER(10) NOT NULL,
	STRE_AUTH_YN VARCHAR(1),
	REDNG_AUTH_YN VARCHAR(1),
	DEL_AUTH_YN VARCHAR(1),
	PRNTG_AUTH_YN VARCHAR(1),
	REG_DT DATETIME DEFAULT SYSDATETIME,
	RGTR_ID VARCHAR(20) DEFAULT 'SYSTEM'
);
ALTER TABLE TB_INDVLZ_MENU_AUTH_R ADD CONSTRAINT PK_TB_INDVLZ_MENU_AUTH_R PRIMARY KEY (MBR_ID,AUTH_GRP_ID,MENU_SN);


/* 개별메뉴권한변경이력 */
DROP SEQUENCE SEQ_TB_INDVLZ_MENU_AUTH_CHNG_H;
CREATE SERIAL SEQ_TB_INDVLZ_MENU_AUTH_CHNG_H START WITH 1 INCREMENT BY 1;
DROP TABLE TB_INDVLZ_MENU_AUTH_CHNG_H;
CREATE TABLE TB_INDVLZ_MENU_AUTH_CHNG_H (
	MBR_ID VARCHAR(20) NOT NULL,
	MENU_SN INTEGER(10) NOT NULL,
	AUTH_GRP_ID VARCHAR(20) NOT NULL,
	CHNG_HIST_SN INTEGER(10) NOT NULL,
	STRE_AUTH_YN VARCHAR(1),
	REDNG_AUTH_YN VARCHAR(1),
	DEL_AUTH_YN VARCHAR(1),
	PRNTG_AUTH_YN VARCHAR(1),
	REG_DT DATETIME DEFAULT SYSDATETIME,
	RGTR_ID VARCHAR(20) DEFAULT 'SYSTEM'
);
ALTER TABLE TB_INDVLZ_MENU_AUTH_CHNG_H ADD CONSTRAINT PK_TB_INDVLZ_MENU_AUTH_CHNG_H PRIMARY KEY (MBR_ID,MENU_SN,AUTH_GRP_ID,CHNG_HIST_SN);


/* 메뉴기본 */
DROP SEQUENCE SEQ_TB_MENU_M;
CREATE SERIAL SEQ_TB_MENU_M START WITH 1 INCREMENT BY 1;
DROP TABLE TB_MENU_M;
CREATE TABLE TB_MENU_M (
	MENU_SN INTEGER(10) NOT NULL,
	UPR_MENU_SN INTEGER(10),
	MENU_NM VARCHAR(200),
	MENU_URL VARCHAR(200),
	MENU_LVL_VL INTEGER(15),
	MENU_SEQ INTEGER(5),
	MENU_EXPLNT VARCHAR(2000),
	REG_DT		DATETIME			DEFAULT	SYSDATETIME 	NOT NULL,
	RGTR_ID		VARCHAR(20)             			NOT NULL,
	MDFCN_DT	DATETIME			DEFAULT	SYSDATETIME  	NOT NULL,
	MDFR_ID		VARCHAR(20)						NOT NULL,
	DEL_YN	 	CHAR(1)			DEFAULT	'N'			NOT NULL
);
ALTER TABLE TB_MENU_M ADD CONSTRAINT PK_TB_MENU_M PRIMARY KEY (MENU_SN);


/* 회원로그내역 */
DROP SERIAL SEQ_TB_MBR_LOG;
CREATE SERIAL SEQ_TB_MBR_LOG START WITH 1 INCREMENT BY 1;
DROP TABLE TB_MBR_LOG;
CREATE TABLE TB_MBR_LOG (
	MBR_LOG_SN INTEGER(10) NOT NULL,
	MBR_ID VARCHAR(20) NOT NULL,
	LOG_DATE VARCHAR(8),
	MENU_SN INTEGER(10),
	LOG_REG_DT DATETIME DEFAULT SYSDATETIME,
	LOG_CNTS VARCHAR(4000),
	DEL_YN CHAR(1) DEFAULT 'N' NOT NULL
);
ALTER TABLE TB_MBR_LOG ADD CONSTRAINT PK_TB_MBR_LOG PRIMARY KEY (MBR_LOG_SN);

/* 첨부파일 */
DROP SERIAL SEQ_TB_ATCH_FILE;
CREATE SERIAL SEQ_TB_ATCH_FILE START WITH 1 INCREMENT BY 1;
DROP TABLE TB_ATCH_FILE;
CREATE TABLE TB_ATCH_FILE
(
	ATCH_FILE_SN         INTEGER(10) NOT NULL ,
	ORGNL_ATCH_FILE_NM   VARCHAR(200) NOT NULL ,
	ATCH_FILE_NM         VARCHAR(200) NOT NULL ,
	ATCH_FILE_SZ         INTEGER(10) NOT NULL ,
	ATCH_FILE_EXTN_NM    VARCHAR(10) NOT NULL ,
	ATCH_FILE_PATH_NM    VARCHAR(200) NOT NULL ,
	REG_DT               DATETIME DEFAULT  SYSDATETIME  NOT NULL ,
	RGTR_ID              VARCHAR(20) NOT NULL ,
	MDFCN_DT             DATETIME DEFAULT  SYSDATETIME  NOT NULL ,
	MDFR_ID              VARCHAR(20) NOT NULL ,
	DEL_YN               CHAR(1) DEFAULT  'N'  NOT NULL 
);
ALTER TABLE TB_ATCH_FILE ADD CONSTRAINT PK1_TB_ATCH_FILE PRIMARY KEY (ATCH_FILE_SN);