/**********************************/
/* Table Name: 직급관리 */
/**********************************/
-- DROP TABLE TB_POSITION;

CREATE TABLE TB_POSITION(
	POSITION_ID		INTEGER(20)		NOT NULL		,
	POSITION_NM		VARCHAR(40)		NOT NULL		,
	DEL_YN	 	    CHAR(1)			DEFAULT	'N'				NOT NULL
);
ALTER TABLE TB_POSITION ADD CONSTRAINT IDX_TB_POSITION_PK PRIMARY KEY (POSITION_ID);

-- ID GENERATE TYPE
-- DELETE FROM JNITSEQ WHERE TABLE_NAME = 'EXTS_CPF_POSITION';
-- INSERT INTO JNITSEQ(TABLE_NAME, NEXT_ID) VALUES ('EXTS_CPF_POSITION', '1');

-- SEQUENCE TYPE
-- DROP SERIAL SEQ_TB_POSITION;
CREATE SERIAL SEQ_TB_POSITION START WITH 1 INCREMENT BY 1;
