DROP TABLE [TABLE_NAME] CASCADE CONSTRAINTS;

/**********************************/
/* Table Name: [Description] */
/**********************************/
CREATE TABLE [TABLE_NAME](
[DDL_COLUMN]
	ISDEL	 	VARCHAR(1)	DEFAULT	'Y'		NOT NULL,
	CREATED	 	DATE	DEFAULT	SYSDATE ,
	CREATED_ID	VARCHAR(20) ,
	MODIFIED	DATE	DEFAULT	SYSDATE ,
	MODIFIED_ID	VARCHAR(20)							
);
ALTER TABLE [TABLE_NAME] ADD CONSTRAINT IDX_[TABLE_NAME]_PK PRIMARY KEY ([FirstColumn]);

COMMENT ON TABLE [TABLE_NAME] is '[Description] 테이블';
[DDL_COMMENT]

-- DELETE FROM JNITSEQ WHERE TABLE_NAME = '[IDGEN_TABLE_NAME]';
INSERT INTO JNITSEQ(TABLE_NAME, NEXT_ID) VALUES ('[IDGEN_TABLE_NAME]', '1');